### ISSUE TITLE
ENHANCE !

### ISSUE THREAD

**Issue by yagarea** [0d9e-tech/web#5]
> ![enhance1](https://github.com/user-attachments/assets/27db87ff-fef6-40be-b4e4-94e5a88a560b)
> ### With our best technology we can examine this dangerous hacker group's page. We need to find a security flaw to catch them.

![1](https://github.com/user-attachments/assets/ca1a9cf8-696b-49d0-b320-ac224c97aa89)

> ![enhance 2](https://github.com/user-attachments/assets/e24f27d2-8144-4951-863f-8bb455aaff3b)
> ### Oh my god, can you see it?!

![2](https://github.com/user-attachments/assets/d55ff30d-5c4e-4094-92ff-84e49dd8dfe8)

> ![enhance 3](https://github.com/user-attachments/assets/7071dda0-ee77-41e2-b110-19cfe44406f6)
> ### Zoom in!

![3](https://github.com/user-attachments/assets/8c8a9a40-bd33-4399-9786-a9d9c5a22b73)

> ![enahnce 4](https://github.com/user-attachments/assets/d36c43ae-bb12-4e20-9df0-6537e69a2d76)
> ### Zooming in

![4](https://github.com/user-attachments/assets/f65f4bc2-bfc8-4af9-b7f2-af99b6890e75)

> ![enahnce 5](https://github.com/user-attachments/assets/00f387a8-7284-4569-8c7d-cafe5ed0fdfd)
> ### Enhance!

![5](https://github.com/user-attachments/assets/4c5dbd00-7f09-47ad-b320-b766514b2647)

> ![enhance 6](https://github.com/user-attachments/assets/eb76a402-1855-4593-9280-2619019cbc82)
> ### Oh... My... God...

![6](https://github.com/user-attachments/assets/46e2717c-b46e-455d-aaa0-d58f88d47cc8)

> 
![enahnce 7](https://github.com/user-attachments/assets/9123eafa-202f-49cc-b8cc-c4d5d2cd4254)

> ## WE GOT THEM!

**Comment by mvolfik** [comment]
ty emoji jsou vypíchaný, každej prohlížeč to renderuje jinak. Buď tam musíme explicitně dát nějakej font kterej to udělá konzistentní, a nebo to udělat jako obrázky

where patch

**Comment by yagarea** [comment]
> where patch
-----> #6

**Comment by yagarea** [comment]
Enhanced in #6
